import { getSupabaseServer } from "@/app/lib/supabase-server";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

export default async function UserPage({ params }: any) {

  const supabase = await getSupabaseServer();

  const { data: images } = await supabase
    .from("image_generation_history")
    .select("id,image_url,prompt,created_at,user_id")
    .eq("user_id", params.id)
    .order("created_at", { ascending: false })
    .limit(50);

  if (!images) {
    return notFound();
  }

  return (

    <main style={{ maxWidth: 1100, margin: "auto", padding: 40 }}>

      <h1>User Creations</h1>

      <p style={{ opacity: 0.6 }}>
        Images generated by this creator
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))",
          gap: 16,
          marginTop: 30
        }}
      >

        {images.map((img: any) => (

          <a
            key={img.id}
            href={`/image/${img.id}`}
            style={{ display: "block" }}
          >

            <img
              src={img.image_url}
              style={{
                width: "100%",
                borderRadius: 10
              }}
            />

          </a>

        ))}

      </div>

    </main>
  );
}
